sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: JgfKt9hRl0biZ5S0OW+u8H2RWSyY1gyTWmNbDXn14Jxxxx+i4dL1yxcfRmSa0bEKEvJcJ+F+22Kkl1R+3nF+4ZQkUGV2swZKu4maM3RMG1MsFws61Qn400EsvhI5DfqBqxeeNXxQn6QfsD62BbTciORs7CYQCcqfoJHz/lsR8YfHYGEM67qCONy4XIk5RlgIM2RUsZ3D43KW93tF+PckE/b/lm+IaXpWAv3g3JmGZPe+XjRC+GkViNys4h2sgjL4dK9iv0ZxMnfInhRf8Est2k1dw+ruXTLy4tvEzV+LA7FZbskzUDqSadzOKPbrp7X75kcvet8YWsYKVSRXi/7FlTivASnqvTwkHAg3kfY569EEajeJHN9KUn5hNSx11Y7rjp461ie1G7AA/xYM7xLJhlhrr2ydFnT7zgY8UFemxYer6uIka6W1QcxZsIVDIvg2VH3ptHneVmTd2GbuloaeWmV7Iu9b5usneCy2iySqUEYOyxxG1fWCIBRmekQlR1FbkfTDwfQpJ0BnvW0E3YNF4RSo5a/V+gGafZEoiWfiXfSIPF2M5mxuxWt5K0VDxuyuO9iDUyiL1tUGdmgTcOea54hlXy+JOTpYj19Tq7wHNfLyMV6DMQYFW0+OinB1YmGOJEs8NFjWwn5ZjoejvIjBQVNraHD/LC/n+b6gO82PABE=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: WrKFJ6YM11A9fYVTSxMqZS3vkz55mRborMdmI6O36GIJvOSyWrP+fx2KRmANLBGSLhZsNSU4qi1RnOuj7IeJS3DF2Z8hv7YyVENCTtRi6vgxB8uYuFscuQgcs2GfTygKrGbR8aIgxJVHbopD8SJhodceDb0ei4XLYaT0uBoN6iIMuY/QJ/xEdv5Cp1KlORckwZhfIPZ+pbYsGDl6G4waylTOgeQ9PvThQifygSmcCAg4tI5GCbCeAwbUEsEnzZaBgMk1SarGmV6J6iqjI2q+CXT9M3j8xH68sus/7lN5TlerVjLpI6Gq6clLoXeDhNwkiXwdbIEBTEHi6ZhM9WuI0Rt8jwH94kK9YYZLQSg+Ihq3MuJCty+bugGQr+hgcEjULHbmRgc+fnJbNa0ijhFTCjMGpGXz4ltqGWXnjsjCT0n7A+uio0w2ZVoM+9WkQbYpX1lkj07gH6hwDoej6bHTPGSOKr1i+1CJ+SlzaJZdeIoXM+RxHQT52wngPiSNlwdqsw2GHnOc1GvJ5wrzRJ4dFYpVIW9WT0ZS46pR1pdZhwNKM2B0TYjJqDIsucbSY+ilMsfrPztRKCQCJPc28F/oN1yuwZbU2mLbXvCRJTrkFYUtQ6EOP+XCnvs/IeGHcsj4CdFKv5VZBEIOozJDAl7+cMjIamTZEWTz2XethIQLhf4=
